// app.js
const express = require("express");
const bodyParser = require("body-parser");
const dotenv = require("dotenv");
const cors = require("cors");
const { GoogleGenerativeAI } = require("@google/generative-ai");

dotenv.config();

const app = express();
const port = process.env.PORT || 8080;

// --- CORS setup: allow your Render static site
app.use(
  cors({
    origin: "https://render-static-site-te8v.onrender.com",
    methods: ["GET", "POST"],
    allowedHeaders: ["Content-Type"],
  })
);

app.use(bodyParser.json({ limit: "10mb" }));
app.use(bodyParser.urlencoded({ extended: true }));

// --- API Key validation
const apiKey = (process.env.GOOGLE_API_KEY || "").trim();
if (!apiKey) {
  console.error("❌ Missing GOOGLE_API_KEY in environment variables");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(apiKey);

// --- Compliance-check endpoint ---
app.post("/compliance-check", async (req, res) => {
  try {
    const { rfqText, proposalText } = req.body;

    if (!rfqText || !proposalText) {
      return res.status(400).json({ error: "Missing RFQ or Proposal text" });
    }

    // Build prompt for Gemini
    const prompt = `
Compare the following two documents for compliance:

RFQ (Request for Quotation):
${rfqText}

Proposal:
${proposalText}

Provide a detailed compliance analysis highlighting strengths, gaps, and suggestions.
`;

    let model;
    try {
      model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    } catch (err) {
      console.warn("⚠️ Flash model not available, falling back to Pro.");
      model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });
    }

    const result = await model.generateContent(prompt);
    const responseText =
      result?.response?.text?.() || "No response generated by AI.";

    res.json({ result: responseText });
  } catch (error) {
    console.error("❌ Backend Error:", error);
    res
      .status(500)
      .json({ error: error.message || "Internal Server Error", stack: error.stack });
  }
});

// --- Health check endpoint ---
app.get("/", (req, res) => {
  res.send("✅ Compliance Backend is running.");
});

// --- Start server ---
app.listen(port, () => {
  console.log(`🚀 Server running on port ${port}`);
});
